// Cue sheet of the Per Weapon film: chapter frames + named event times derived from the spoken words
// (generated by scripts/audio/pw-cues.mjs).
import data from './cues.json';

export const FPS = data.fps;
export const OV = data.ov;
export const TOTAL = data.total;
export const CHAPTERS = data.chapters as {id: string; startF: number; durF: number}[];
const CH: Record<string, {startF: number; durF: number}> = Object.fromEntries(CHAPTERS.map((c) => [c.id, c]));
const CUES = data.cues as Record<string, number>;

/** seconds on the video timeline */
export const cue = (name: string): number => {
	const v = CUES[name];
	if (v === undefined) throw new Error(`unknown cue ${name}`);
	return v;
};

/** local frame (inside chapter `ch`) of cue `name`, plus an optional offset in seconds */
export const lf = (ch: string, name: string, off = 0): number => Math.round((cue(name) - CH[ch].startF / FPS + off) * FPS);

/** 1 while local frame f is inside [a, b] */
export const win = (f: number, a: number, b: number) => (f >= a && f <= b ? 1 : 0);
